### ISSUE TITLE
RedoxRabbit Review

### ISSUE THREAD

**Issue by grantrobertsmith** [100health/redox-rabbit#10]
redox-rabbit.js
Line Number: 8
Comment: Can this go in the config file?

Line Number: 10-15
Comment: These all seem like properties that are basically private to the file. How about we move isConnecting and channel out of Rabbit unless we really need access to them from somewhere else in the code.

Line Number: 25
Comment: Use ===

Line Number: 155
Comment: Use ===

Line Number: 64
Comment: can we specify null for err here, since this will always be the case anyway at this point

Line Number: 58
Comment: If we make a connection and then err when making the channel, do we want to close out the connection? I'm unsure if we could leak resources in this case.

Line Number: 78
Comment: Similar to previous, when we're going through the destroy/clean-up process here, it may be possible to leak resources depending on the failure modes of the amqp library.

Line Number: (functions send, pause, resume)
Comment: Are we fine ignoring the error cases here? What causes them?

Line Number: 168-172
Comment: Let's build the args object all at once by moving the ordered and destination fields inside the initial declaration.

Line Number: 187 (observe)
Comment: missing function header

Line Number: 239 (messageCallback)
Comment: missing function header

**Comment by matt-cook** [comment]
Follow up issue for handling RabbitMQ errors: https://github.com/100health/redox-rabbit/issues/18
