### ISSUE TITLE
Notes from review

### ISSUE THREAD

**Issue by tobalsgithub** [100health/redox-rabbit#5]
For coding style, reference the notes I made here: https://github.com/100health/redox-rabbit-broker/issues/2

### Server

"Connect to kibana" - https://github.com/100health/redox-rabbit/blob/master/lib/server.js#L12
Kibana again :) - https://github.com/100health/redox-rabbit/blob/master/lib/server.js#L45

What is an `isConfirmChannel`?

Any reason that `channel` is defined on Server, but `connection` is not?

Need a return statement here: https://github.com/100health/redox-rabbit/blob/master/lib/server.js#L58

### Consumer

Any thoughts on what we need to be doing here? https://github.com/100health/redox-rabbit/blob/master/lib/consumer.js#L25

Might be nice to pull this `reply` function out and make it its own function. Would make it easier to test, and also makes it a little easier to read this, as it becomes clear that `reply` is a callback that will be called multiple times in the future, not something that is part of the initial call to `consume`, if that makes sense. https://github.com/100health/redox-rabbit/blob/master/lib/consumer.js#L22

I find it a little nicer to do checks like the `cb` check at the top of the function, rather than down towards the bottom. Could probably just put this at the top `cb = cb || function(){};`

### Producer

At the very end of this line, can't we just pass in `cb`, rather than `err => cb(err)`? https://github.com/100health/redox-rabbit/blob/master/lib/producer.js#L48

### Config

Eventually we'll have to allow more options than just localhost. I wonder if it would make sense to allow these config options to be passed in somehow, either by the consumer and producer, or as a global option the user could set once and then the consumer and producer would automatically use that.

**Comment by matt-cook** [comment]
`channel` is defined publicly on `Server` since it needs to be available in instances. `connection` is private and is only used internally.
